name: brainwavelogger
channels:
  - defaults
dependencies:
  - python=3.12
  - ipykernel=6.29
  - matplotlib=3.10
  - numpy=1.26
  - pandas=2.3
  - scikit-learn=1.7
  - scipy=1.16
  - seaborn=0.13
  - tensorflow=2.18
  - pytest=8.4
  - fastapi=0.116
  - pip=25.2
  - pip:
    - pylsl==1.17
    - fastapi[standard]
