export const recordedSessions = [
    {minsBeta:12,minsAlpha:11,minsTheta:13,seshType:"none"},
    {minsBeta:22,minsAlpha:21,minsTheta:23,seshType:"none"},
    {deltaPower: 94, thetaPower: 41, alphaPower: 35, betaPower: 94, gammaPower: 72, sessionMinutes: 35, percentKept: 46, seshType: "none"},
    {deltaPower: 94, thetaPower: 40, alphaPower: 34, betaPower: 94, gammaPower: 71, sessionMinutes: 35, percentKept: 46, seshType: none},
    {deltaPower: 135, thetaPower: 18, alphaPower: 12, betaPower: 28, gammaPower: 7, sessionMinutes: 76, percentKept: 85, seshType: none},
    {deltaPower: 173, thetaPower: 18, alphaPower: 9, betaPower: 12, gammaPower: 1, sessionMinutes: 39, percentKept: 90, seshType: none},
    {deltaPower: 165, thetaPower: 31, alphaPower: 21, betaPower: 44, gammaPower: 10, sessionMinutes: 40, percentKept: 75, seshType: none},
    {deltaPower: 87, thetaPower: 9, alphaPower: 5, betaPower: 9, gammaPower: 1, sessionMinutes: 44, percentKept: 89, seshType: none},
    {deltaPower: 102, thetaPower: 24, alphaPower: 18, betaPower: 62, gammaPower: 25, sessionMinutes: 32, percentKept: 36, seshType: none},
    {deltaPower: 0, thetaPower: 0, alphaPower: 0, betaPower: 0, gammaPower: 0, sessionMinutes: 0, percentKept: 0, seshType: none},
    {deltaPower: 109, thetaPower: 56, alphaPower: 31, betaPower: 78, gammaPower: 31, sessionMinutes: 35, percentKept: 64, seshType: none},
    {deltaPower: 150, thetaPower: 70, alphaPower: 56, betaPower: 131, gammaPower: 74, sessionMinutes: 19, percentKept: 39, seshType: none},
    {deltaPower: 140, thetaPower: 17, alphaPower: 10, betaPower: 17, gammaPower: 4, sessionMinutes: 33, percentKept: 81, seshType: none},
    {deltaPower: 171, thetaPower: 28, alphaPower: 16, betaPower: 28, gammaPower: 4, sessionMinutes: 22, percentKept: 70, seshType: none},
    {deltaPower: 151, thetaPower: 12, alphaPower: 5, betaPower: 7, gammaPower: 1, sessionMinutes: 27, percentKept: 92, seshType: none},
    {deltaPower: 246, thetaPower: 70, alphaPower: 45, betaPower: 91, gammaPower: 41, sessionMinutes: 20, percentKept: 41, seshType: none},
    {deltaPower: 99, thetaPower: 9, alphaPower: 5, betaPower: 10, gammaPower: 3, sessionMinutes: 21, percentKept: 73, seshType: none},
    {deltaPower: 92, thetaPower: 13, alphaPower: 10, betaPower: 17, gammaPower: 1, sessionMinutes: 21, percentKept: 97, seshType: none},
    {deltaPower: 112, thetaPower: 10, alphaPower: 6, betaPower: 13, gammaPower: 2, sessionMinutes: 24, percentKept: 96, seshType: none},
    {deltaPower: 75, thetaPower: 28, alphaPower: 22, betaPower: 63, gammaPower: 49, sessionMinutes: 34, percentKept: 50, seshType: none},
    {deltaPower: 116, thetaPower: 16, alphaPower: 13, betaPower: 23, gammaPower: 3, sessionMinutes: 7, percentKept: 86, seshType: none},
    {deltaPower: 94, thetaPower: 40, alphaPower: 34, betaPower: 94, gammaPower: 71, sessionMinutes: 35, percentKept: 46, seshType: none},
    {deltaPower: 151, thetaPower: 26, alphaPower: 21, betaPower: 64, gammaPower: 27, sessionMinutes: 33, percentKept: 86, seshType: none},
    {deltaPower: 95, thetaPower: 57, alphaPower: 44, betaPower: 108, gammaPower: 64, sessionMinutes: 16, percentKept: 44, seshType: none},
    {deltaPower: 151, thetaPower: 23, alphaPower: 16, betaPower: 51, gammaPower: 17, sessionMinutes: 65, percentKept: 81, seshType: none},
    {deltaPower: 46, thetaPower: 6, alphaPower: 6, betaPower: 14, gammaPower: 1, sessionMinutes: 0, percentKept: 99, seshType: none},
]